### ISSUE TITLE
error in assembly results in fatal unexpected error

### ISSUE THREAD

**Issue by stefandrissen** [stever/zxcoder#9]
On https://zxcoder.org/ assembly tab, introduce a typo, for example:

    ld hl,hellox

And then press the play button.

````
Sorry, an unexpected error occurred.

Error message is:
[Exception] [object Object]

Press one of the following buttons:
````

All buttons result in your changes being lost, the only safe way to get back is to click on 'ZX Coder'

**Comment by stever** [comment]
The commit 22e8239 resolved this issue.
